; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32s3mini

[env:esp32mini]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
lib_deps = 
	knolleary/PubSubClient @ ^2.8
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson @ ^7.0.4
build_flags = -std=gnu++17

[env:esp32s3mini]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

upload_port = COM26
monitor_port = COM26

board_build.filesystem = spiffs
board_build.partitions = partitions/default.csv
lib_deps =
	knolleary/PubSubClient @ ^2.8
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson @ ^7.0.4
	adafruit/Adafruit NeoPixel @ ^1.12.0
build_flags =
	-std=c++2a
	-DBOARD_HAS_PSRAM

[env:esp32s3mini_ota]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

upload_protocol = espota
upload_port = tombask.local

board_build.filesystem = spiffs
board_build.partitions = partitions/default.csv
lib_deps =
	knolleary/PubSubClient @ ^2.8
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson @ ^7.0.4
	adafruit/Adafruit NeoPixel @ ^1.12.0
build_flags =
	-std=c++2a
	-DBOARD_HAS_PSRAM
upload_flags =
    --auth=password